import { Product } from "@/types/product";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Laptop Pro",
    category: "Electronics",
    description: "High-performance laptop with 16GB RAM and 1TB SSD",
    price: 1299.99,
    stock: 10,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    name: "Wireless Headphones",
    category: "Electronics",
    description: "Noise-cancelling Bluetooth headphones with 30h battery",
    price: 299.99,
    stock: 25,
    createdAt: new Date("2024-01-14"),
  },
  {
    id: 3,
    name: "Cotton T-Shirt",
    category: "Clothing",
    description: "100% cotton crew neck t-shirt, available in multiple colors",
    price: 24.99,
    stock: 50,
    createdAt: new Date("2024-01-13"),
  },
  {
    id: 4,
    name: "Smartphone X",
    category: "Electronics",
    description: "Latest smartphone with triple camera setup",
    price: 899.99,
    stock: 15,
    createdAt: new Date("2024-01-12"),
  },
  {
    id: 5,
    name: "Running Shoes",
    category: "Footwear",
    description: "Lightweight running shoes with cushioned soles",
    price: 89.99,
    stock: 30,
    createdAt: new Date("2024-01-11"),
  },
  {
    id: 6,
    name: "Coffee Maker",
    category: "Home Appliances",
    description: "Programmable coffee maker with thermal carafe",
    price: 79.99,
    stock: 20,
    createdAt: new Date("2024-01-10"),
  },
  {
    id: 7,
    name: "Backpack",
    category: "Accessories",
    description: "Water-resistant backpack with laptop compartment",
    price: 49.99,
    stock: 40,
    createdAt: new Date("2024-01-09"),
  },
  {
    id: 8,
    name: "Desk Lamp",
    category: "Home Office",
    description: "Adjustable LED desk lamp with touch controls",
    price: 34.99,
    stock: 35,
    createdAt: new Date("2024-01-08"),
  },
];
